language: node_js
os:
  - linux
  - windows
  - osx
matrix:
  include:
    - node_js:
      - "8"
    - node_js:
      - "10"
    - node_js:
      - "12"
install:
    - npm install
script:
    - test
