// const uri = "https://www.w3.org/TR/json-ld/#syntax-tokens-and-keywords";

export const JsonLd = {
    blank: "_:"
    ,"@base": "@base"
    ,"@container": "@container"
    ,"@context": "@context"
    ,"@direction": "@direction"
    ,"@graph": "@graph"
    ,"@id": "@id"
    ,"@import": "@import"
    ,"@included": "@included"
    ,"@index": "@index"
    ,"@json": "@json"
    ,"@language": "@language"
    ,"@list": "@list"
    ,"@nest": "@nest"
    ,"@none": "@none"
    ,"@prefix": "@prefix"
    ,"@propagate": "@propagate"
    ,"@protected": "@protected"
    ,"@reverse": "@reverse"
    ,"@set": "@set"
    ,"@type": "@type"
    ,"@value": "@value"
    ,"@version": "@version"
    ,"@vocab": "@vocab"
};
