name: Run Tests
on: [push]
jobs:
  test_unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      shell: bash
      run: |
        npm install
        cd ./test
        npm test
      env:
        CI: true
  test_win:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - run: git config --global core.autocrlf true
    - run: git config --global core.whitespace cr-at-eol
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        cd .\test
        npm test-win
      env:
        CI: true
