name: Run Tests
on:
  push:
  pull_request:
#  schedule:
#  - cron: '0 23 * * *'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      shell: bash
      run: |
        npm install
        cd ./test
        npm install
        cd ..
        npm test
      env:
        CI: true
