name: Tests (Functional)
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
#  schedule:
#  - cron: '0 23 * * *'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [16.x, 18.x, 19.x]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      shell: bash
      run: |
        echo "| Testing against dependencies locked by package-lock.json"
        npm install
        cd ./test
        npm install
        cd ..
        npm test
      env:
        CI: true
